CREATE TABLE QNA_ANS(

	QNA_ANS_SEQ NUMBER(8) NOT NULL,
	QNA_ANS_ID VARCHAR2(50),
	QNA_ANS_CONTENT VARCHAR2(1000) NOT NULL,
	QNA_ANS_WDATE DATE NOT NULL,
	QNA_ANS_REF NUMBER(8) NOT NULL,
	QNA_ANS_DEL NUMBER(1) NOT NULL
);


ALTER TABLE QNA_ANS
ADD CONSTRAINT FK_QAANS_ID FOREIGN KEY(QNA_ANS_ID)
REFERENCES MEMBER(ID);

SELECT * FROM QNA_ANS

CREATE SEQUENCE QNA_ANS_SEQ
START WITH 1
INCREMENT BY 1;

DROP SEQUENCE QNA_ANS_SEQ

DROP TABLE QNA_ANS CASCADE CONSTRAINTS;
