CREATE TABLE REV_BOARD
	(
    REV_SEQ NUMBER(8) NOT NULL,
    REV_ID VARCHAR2(50) NOT NULL,
    REV_TITLE VARCHAR2(50)NOT NULL,
    REV_CONTENT VARCHAR2(2000) NOT NULL,
    REV_SCORE NUMBER(8) NOT NULL,
    REV_FILENAME VARCHAR2(50),
    REV_WDATE DATE NOT NULL,  
    REV_DEL NUMBER(2) NOT NULL,
    REV_PRD_NUM NUMBER(8)
    ); 
    
ALTER TABLE REV_BOARD
ADD CONSTRAINT FK_REV_PRD_NUM FOREIGN KEY(REV_PRD_NUM)
REFERENCES PRODUCT(PRD_NUM);

SELECT * FROM REV_BOARD;

CREATE SEQUENCE SEQ_REV
START WITH 1
INCREMENT BY 1;

DROP TABLE REV_BOARD CASCADE CONSTRAINTS;

INSERT INTO REV_BOARD
VALUES (SEQ_REV.NEXTVAL, 'BBB', '별로임', 'ㅎㅎ', 1, NULL, SYSDATE, 0, 112);

DROP TABLE REV_BOARD;
DROP SEQUENCE SEQ_REV;